### ISSUE TITLE
Preparar os wireframes das principais telas

### ISSUE THREAD

**Issue by apaulovp** [ayanara/read4life#1]
Preparar os wireframes das 4 principais telas.

- [x] Página inicial para conhecer o site
- [x] Página de login
- [x] Página principal (página inicial do usuário)
- [x] Página de detalhe do livro

**Comment by ayanara** [comment]
Template [Figma](https://www.figma.com/file/uvRDBCwIwJf5c4Rbe6YykN/landing-page-wireframe-biblioteca?node-id=0%3A1)
