### ISSUE TITLE
Preparar design das 4 principais páginas

### ISSUE THREAD

**Issue by apaulovp** [ayanara/read4life#2]
**Esta tarefa depende da conclusão da #1**

Preparar layout e design no Figma das 4 principais páginas do sistema.

Esse layout será usado como base para a criação das páginas HTML e CSS.

Se basear no wireframe criado em #1 .

Designs para criar:
- [x] Página inicial do sistema (usuário não logado)
- [x] Página de login
- [x] Página principal (página inicial de um usuário logado)
- [x] Página de detalhe de um livro (para onde vai ao clicar em um livro)

**Comment by ayanara** [comment]
https://www.figma.com/file/uvRDBCwIwJf5c4Rbe6YykN/landing-page-wireframe-biblioteca?node-id=18%3A100

**Comment by ayanara** [comment]
https://www.figma.com/file/uvRDBCwIwJf5c4Rbe6YykN/landing-page-wireframe-biblioteca?node-id=18%3A100
