### ISSUE TITLE
Criar o README do projeto

### ISSUE THREAD

**Issue by apaulovp** [ayanara/read4life#3]
Crie o primeiro arquivo do projeto como sendo o `README.MD`, e descreva sobre o que irá se tratar esse projeto.

Caso se baseie em alguma documentação para padrões de README, favor deixar descrito nessa issue a referência.

Para este projeto iremos usar o Github Flow, que é basicamente:
- Temos um branch `main` onde tudo que estiver nele estará em produção.
- Todos os branchs são feitos a partir do `main` e serão realizados merge de volta para o `main`.

Ao criar seus _branches_, e _pull requests_ vincule eles ao issue, de modo que possamos rastrear qual foi o _branch_ que resolveu qual _issue_.

**Comment by ayanara** [comment]
Fiz, de forma simples.
